package com.ascendra.ai.ui.screens
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.ascendra.ai.domain.ai.AITutorEngine
import com.ascendra.ai.domain.games.GamesEngine
import com.ascendra.ai.domain.progress.ProgressEngine
import com.ascendra.ai.domain.quiz.QuizEngine
import com.ascendra.ai.domain.speech.SpeechEngine
import com.ascendra.ai.domain.syllabus.SyllabusEngine
import com.ascendra.ai.ui.components.HolographicCard
import com.ascendra.ai.ui.theme.AscendraColors
@Composable fun SplashScreen(onFinish:()->Unit){Box(Modifier.fillMaxSize()){Column(Modifier.fillMaxSize(),verticalArrangement=Arrangement.Center,horizontalAlignment=Alignment.CenterHorizontally){Text("A",style=MaterialTheme.typography.displayLarge.copy(color=AscendraColors.Platinum));Text("ASCENDRA",style=MaterialTheme.typography.headlineMedium.copy(color=AscendraColors.TextPrimary,letterSpacing=androidx.compose.ui.unit.TextUnit(6f,androidx.compose.ui.unit.TextUnitType.Sp)));Text("LEARN BEYOND LIMITS",style=MaterialTheme.typography.labelSmall.copy(color=AscendraColors.TextSecondary))}};LaunchedEffect(Unit){kotlinx.coroutines.delay(1500);onFinish()}}
@Composable fun LoginScreen(onLogin:()->Unit){LazyColumn(Modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){item{HolographicCard(accent=AscendraColors.Blue){Text("LOGIN / SIGNUP",color=AscendraColors.GoldGlow,style=MaterialTheme.typography.labelSmall);Spacer(Modifier.height(8.dp));Text("Welcome MADHA",color=AscendraColors.TextPrimary);Button(onClick=onLogin,modifier=Modifier.fillMaxWidth().padding(top=12.dp)){Text("Continue with OTP")}}}}}
@Composable fun HomeScreen(){val s=remember{SyllabusEngine.getTree()};val p=remember{ProgressEngine().getProgress()};LazyColumn(Modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){item{HolographicCard(accent=AscendraColors.Violet){Text("Good morning, MADHA",color=AscendraColors.TextPrimary);Text("Business Comm mastery ${(p.mastery["Business Comm"]!!*100).toInt()}% • Continue Chapter 3?",color=AscendraColors.TextSecondary,style=MaterialTheme.typography.bodySmall)}};item{HolographicCard(accent=AscendraColors.Blue){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("ENERGY 82%",style=MaterialTheme.typography.bodySmall);Text("${p.totalXP/1000}k PULSE",style=MaterialTheme.typography.bodySmall);Text("${p.vault} VAULT",color=AscendraColors.GoldGlow,style=MaterialTheme.typography.bodySmall)};LinearProgressIndicator(progress={0.73f},modifier=Modifier.fillMaxWidth().padding(top=10.dp),color=AscendraColors.GoldGlow,trackColor=AscendraColors.Border)}};item{HolographicCard{Text("Syllabus: ${s.name} -> ${s.children.first().name} -> BBA",color=AscendraColors.TextSecondary,style=MaterialTheme.typography.bodySmall)}}}}
@Composable fun AITutorScreen(){val e=remember{AITutorEngine()};LazyColumn(Modifier.fillMaxSize().padding(20.dp)){item{HolographicCard(accent=AscendraColors.Violet){Text("AI TUTOR - Curriculum Aware",color=AscendraColors.VioletLight,style=MaterialTheme.typography.labelSmall);Spacer(Modifier.height(8.dp));Text(e.getResponse("Explain Ch3","Business Comm"),color=AscendraColors.TextPrimary,style=MaterialTheme.typography.bodyMedium)}}}}
@Composable fun ExamsScreen(){val q=remember{QuizEngine().generateAdaptive(0.68f,"BC")};LazyColumn(Modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{HolographicCard(accent=AscendraColors.Rose){Text("MOCK TESTS - Adaptive 10 Qs",color=AscendraColors.Rose,style=MaterialTheme.typography.labelSmall)}};items(q.size){i->HolographicCard{Text(q[i].text,style=MaterialTheme.typography.bodySmall)}}}}
@Composable fun GamesScreen(){val g=remember{GamesEngine().getNebulaSyncGame()};LazyColumn(Modifier.fillMaxSize().padding(20.dp)){item{HolographicCard(accent=AscendraColors.Teal){Text("GAMES - Real Games Engine",color=AscendraColors.TealLight,style=MaterialTheme.typography.labelSmall);Spacer(Modifier.height(8.dp));Text("Nebula Sync Protocol - ${(g.nebulaSync*100).toInt()}%",color=AscendraColors.TextPrimary);LinearProgressIndicator(progress={g.nebulaSync},modifier=Modifier.fillMaxWidth().padding(top=8.dp),color=AscendraColors.Teal)}}}}
@Composable fun SpeakScreen(){val c=remember{SpeechEngine().getDailyChallenge()};LazyColumn(Modifier.fillMaxSize().padding(20.dp)){item{HolographicCard(accent=AscendraColors.Gold){Text("SPOKEN ENGLISH - 5min challenge",color=AscendraColors.GoldGlow,style=MaterialTheme.typography.labelSmall);Spacer(Modifier.height(8.dp));Text(c.prompt,style=MaterialTheme.typography.bodyMedium);Text("Target: ${c.target}",color=AscendraColors.TextSecondary,style=MaterialTheme.typography.bodySmall)}}}}
@Composable fun GenericThemedScreen(title:String,subtitle:String="Powered by Ascendra Engines"){LazyColumn(Modifier.fillMaxSize().padding(20.dp)){item{HolographicCard{Text(title,color=AscendraColors.TextPrimary,style=MaterialTheme.typography.headlineMedium);Spacer(Modifier.height(8.dp));Text(subtitle,color=AscendraColors.TextSecondary,style=MaterialTheme.typography.bodySmall)}}}}
